<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>dev.mechana</groupId>
    <artifactId>mechana-parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
  </parent>

  <artifactId>mechana-server</artifactId>
  <name>Mechana :: Server</name>

  <dependencies>
    <dependency>
      <groupId>com.github.spotbugs</groupId>
      <artifactId>spotbugs-annotations</artifactId>
      <version>4.9.8</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.pdfbox</groupId>
      <artifactId>pdfbox</artifactId>
      <version>${pdfbox.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.mechana</groupId>
      <artifactId>mechana-plugin-blender-render</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.mechana</groupId>
      <artifactId>mechana-coordinator</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.mechana</groupId>
      <artifactId>mechana-protocol</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.mechana</groupId>
      <artifactId>mechana-plugin-fractal-render</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.mechana</groupId>
      <artifactId>mechana-plugin-ocr-tesseract</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.mechana</groupId>
      <artifactId>mechana-plugin-video</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.6.0</version>
        <configuration>
          <createDependencyReducedPom>false</createDependencyReducedPom>
          <finalName>mechana-server</finalName>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>shade</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <mainClass>dev.mechana.server.ServerMain</mainClass>
                </transformer>
              </transformers>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
